# 导入已有的节点映射
from .QZ_ResolutionPreset import NODE_CLASS_MAPPINGS as RESOLUTION_PRESET_MAPPINGS
from .QZ_ResolutionPreset import NODE_DISPLAY_NAME_MAPPINGS as RESOLUTION_PRESET_DISPLAY_MAPPINGS

# 导入新节点的映射
from .QZ_WanFrame import NODE_CLASS_MAPPINGS as WAN_FRAME_MAPPINGS
from .QZ_WanFrame import NODE_DISPLAY_NAME_MAPPINGS as WAN_FRAME_DISPLAY_MAPPINGS

# 合并所有节点的映射
NODE_CLASS_MAPPINGS = {
    **RESOLUTION_PRESET_MAPPINGS,
    ** WAN_FRAME_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **RESOLUTION_PRESET_DISPLAY_MAPPINGS,
    ** WAN_FRAME_DISPLAY_MAPPINGS
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
