from .QZ_ResolutionPreset import NODE_CLASS_MAPPINGS as RESOLUTION_PRESET_MAPPINGS
from .QZ_ResolutionPreset import NODE_DISPLAY_NAME_MAPPINGS as RESOLUTION_PRESET_DISPLAY_MAPPINGS

from .QZ_WanFrame import NODE_CLASS_MAPPINGS as WAN_FRAME_MAPPINGS
from .QZ_WanFrame import NODE_DISPLAY_NAME_MAPPINGS as WAN_FRAME_DISPLAY_MAPPINGS
from .QZ_FrameHold import NODE_CLASS_MAPPINGS as FRAME_HOLD_MAPPINGS
from .QZ_FrameHold import NODE_DISPLAY_NAME_MAPPINGS as FRAME_HOLD_DISPLAY_MAPPINGS


NODE_CLASS_MAPPINGS = {
    **RESOLUTION_PRESET_MAPPINGS,
    ** WAN_FRAME_MAPPINGS,
    **FRAME_HOLD_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    ** RESOLUTION_PRESET_DISPLAY_MAPPINGS,
    **WAN_FRAME_DISPLAY_MAPPINGS,
    ** FRAME_HOLD_DISPLAY_MAPPINGS
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
    
